#!/usr/bin/make -f
# DSP-only LV2 build. NAME = the bundle name; the binary is <NAME>_dsp.so.
NAME = simple-echo
FILES_DSP = SimpleEchoPlugin.cpp
include ../../dpf/Makefile.plugins.mk
TARGETS = lv2_dsp
all: $(TARGETS)
