#!/usr/bin/env python3
"""Write ALL-IN-ONE.md: everything a chat-only AI needs, in one file to attach.

    python3 tools/make_all_in_one.py [--cookbook <mod-plugin-cookbook checkout>]

Some chat apps can't fetch GitHub files (GitHub blocks /tree/ and /raw/ for bots,
and some apps refuse raw.githubusercontent.com or URLs not given by the user).
ALL-IN-ONE.md is the fallback: AGENTS.md, the cookbook's recipe prompt (which
includes its worked gain.mk), the docs a single-.mk build needs, and the template
plugin. Re-run it whenever those change; the release checklist does.
Without --cookbook, the cookbook prompt is fetched from GitHub.
"""
import argparse, datetime, os, subprocess, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COOKBOOK_RAW = 'https://raw.githubusercontent.com/mod-audio/mod-plugin-cookbook/main/'
DOCS = ['docs/effect-profile.md', 'docs/path-a-single-recipe.md', 'docs/lv2-and-mod-rules.md',
        'docs/dsp.md', 'docs/hardware-feedback.md', 'docs/modgui.md']
TEMPLATE = [('templates/plugin/plugins/simple-echo/SimpleEchoPlugin.cpp', 'cpp'),
            ('templates/plugin/plugins/simple-echo/DistrhoPluginInfo.h', 'cpp'),
            ('templates/plugin/plugins/simple-echo/Makefile', 'makefile'),
            ('templates/plugin/bundle/simple-echo.lv2/manifest.ttl', 'turtle'),
            ('templates/plugin/bundle/simple-echo.lv2/simple-echo.ttl', 'turtle')]


def cookbook(path, rel):
    if path:
        return open(os.path.join(path, rel)).read()
    with urllib.request.urlopen(COOKBOOK_RAW + rel) as r:
        return r.read().decode()


def demote(md):
    """Push every heading down one level so each file sits under its own heading."""
    out, fence = [], False
    for line in md.splitlines():
        if line.startswith('```'):
            fence = not fence
        out.append('#' + line if (not fence and line.startswith('#')) else line)
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cookbook')
    a = ap.parse_args()
    rd = lambda p: open(os.path.join(ROOT, p)).read()
    try:
        rev = subprocess.check_output(['git', '-C', ROOT, 'rev-parse', '--short', 'HEAD'], text=True).strip()
    except Exception:
        rev = 'unknown'
    parts = ['''# MOD Plugin Playbook: all in one

Generated by `tools/make_all_in_one.py` on %s from playbook commit `%s`. Don't edit by hand.

**For the AI reading this:** this file stands in for the repo when you can't fetch it. It holds `AGENTS.md` (start there, and follow its kick-off), the MOD cookbook's recipe prompt with its worked example, the docs a single-`.mk` build needs, and the template plugin. Where `AGENTS.md` says to fetch or read a file that is below, use the copy below. Files not included here (tests and tools) need a shell; say which checks you couldn't run.

**For the person:** attach this one file to a chat with any AI and say what plugin you'd like.

Licences: the playbook is GPL-3.0-or-later. The cookbook prompt is MIT, Copyright (c) 2026 MOD Audio Limited (notice at its end).
''' % (datetime.date.today().isoformat(), rev)]
    parts.append('# 1. AGENTS.md\n\n' + demote(rd('AGENTS.md')))
    cb = cookbook(a.cookbook, 'prompts/plugin-from-idea.md')
    lic = cookbook(a.cookbook, 'LICENSE')
    parts.append('# 2. The MOD plugin cookbook: prompts/plugin-from-idea.md\n\nFrom github.com/mod-audio/mod-plugin-cookbook. Read it as the foundation; `AGENTS.md` lists where the playbook overrides it.\n\n'
                 + demote(cb) + '\n\n```text\n' + lic.strip() + '\n```')
    for i, p in enumerate(DOCS, 3):
        parts.append('# %d. %s\n\n%s' % (i, p, demote(rd(p))))
    n = 3 + len(DOCS)
    tpl = ['# %d. The template plugin (an echo; parts tagged by trait)\n' % n]
    for p, lang in TEMPLATE:
        tpl.append('## %s\n\n```%s\n%s\n```' % (p, lang, rd(p).rstrip()))
    parts.append('\n\n'.join(tpl))
    out = os.path.join(ROOT, 'ALL-IN-ONE.md')
    open(out, 'w').write('\n\n---\n\n'.join(parts) + '\n')
    print('wrote %s (%d KB)' % (out, os.path.getsize(out) // 1024))


if __name__ == '__main__':
    main()
